name: build and publish a release

on:
  release:
    types: [published]

jobs:
  unit-tests:
    uses: kosi-libs/kodein-internal-github-actions/.github/workflows/unit-tests.yml@main
  instrumentation-tests:
    uses: kosi-libs/kodein-internal-github-actions/.github/workflows/check-with-android.yml@main

  upload-release:
    runs-on: macOS-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_TOKEN_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.PGP_SIGNING_KEY }}
      GPG_PRIVATE_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
      - name: Upload
        run: ./gradlew publishAggregationToCentralPortal
        shell: bash
