name: build and publish a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/*'
      - 'kotlin-*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

jobs:
  unit-tests:
    uses: kosi-libs/kodein-internal-github-actions/.github/workflows/unit-tests.yml@main
  instrumentation-tests:
    uses: kosi-libs/kodein-internal-github-actions/.github/workflows/check-with-android.yml@main

  upload-snapshot:
    needs:
      - unit-tests
      - instrumentation-tests
    runs-on: macOS-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.sonatype_username }}
      SONATYPE_PASSWORD: ${{ secrets.sonatype_password }}
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
      - name: Upload
        run: ./gradlew publishAllPublicationsToOssrhStagingRepository -PgitRef=${{ github.ref }} -Psnapshot=true
        shell: bash
