name: build and publish a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/*'
      - 'kotlin-*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

env:
  SONATYPE_USERNAME: ${{ secrets.sonatype_username }}
  SONATYPE_PASSWORD: ${{ secrets.sonatype_password }}

jobs:
  build-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      # Host only for MacOS / Windows
      - name: Check (macos / windows)
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew hostOnlyTest
        shell: bash
      - name: Check Android
        if: matrix.os == 'macOS-latest'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          ndk: 21.3.6528147
          cmake: 3.10.2.4988404
          script: ./gradlew connectedCheck
      - name: Upload (macos / windows)
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew hostOnlyPublish -PgitRef=${{ github.ref }} -Psnapshot=true
        shell: bash
      # Linux / JVM / JS
      - name: Check (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew check
        shell: bash
      - name: Upload (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew publishAllPublicationsToOssrhStagingRepository -PgitRef=${{ github.ref }} -Psnapshot=true
        shell: bash