name: check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: macOS-latest
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
      - name: Check
        run: ./gradlew check
        shell: bash

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
      - name: Check with Android
        uses: kosi-libs/kodein-internal-github-actions/checkWithAndroid@main
